[package]
name = "intermezzos"
version = "0.1.0"
authors = ["steveklabnik <steve@steveklabnik.com>"]

[package.metadata.bootimage]
default-target = "intermezzos.json"

[workspace]

[dependencies]
rlibc = "1.0"
bootloader_precompiled = "0.2.0"
x86 = "0.12.0"

[dependencies.vga]
path = "vga"

[[bin]]
name = "intermezzos"
test = false

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
